// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS17YEEwdSpIDjfOcEd5UVtvrppDbJxyc',
    appId: '1:235317509482:web:034fa7b74b8ca5033df913',
    messagingSenderId: '235317509482',
    projectId: 'tapasya-app-and-web',
    authDomain: 'tapasya-app-and-web.firebaseapp.com',
    storageBucket: 'tapasya-app-and-web.firebasestorage.app',
    measurementId: 'G-C0ZNEVSLL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0duK_n_ZsZ57DVBP_VSyvhcJj-6F6J-U',
    appId: '1:235317509482:android:5bb7950b8c4c90483df913',
    messagingSenderId: '235317509482',
    projectId: 'tapasya-app-and-web',
    storageBucket: 'tapasya-app-and-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDegFE0_VumJJNFB6LVMAk8Ge9HyxR5_HU',
    appId: '1:235317509482:ios:a4ff565c672a40663df913',
    messagingSenderId: '235317509482',
    projectId: 'tapasya-app-and-web',
    storageBucket: 'tapasya-app-and-web.firebasestorage.app',
    iosBundleId: 'com.example.tapasyaVendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDegFE0_VumJJNFB6LVMAk8Ge9HyxR5_HU',
    appId: '1:235317509482:ios:a4ff565c672a40663df913',
    messagingSenderId: '235317509482',
    projectId: 'tapasya-app-and-web',
    storageBucket: 'tapasya-app-and-web.firebasestorage.app',
    iosBundleId: 'com.example.tapasyaVendorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS17YEEwdSpIDjfOcEd5UVtvrppDbJxyc',
    appId: '1:235317509482:web:9eea82f4900ec45e3df913',
    messagingSenderId: '235317509482',
    projectId: 'tapasya-app-and-web',
    authDomain: 'tapasya-app-and-web.firebaseapp.com',
    storageBucket: 'tapasya-app-and-web.firebasestorage.app',
    measurementId: 'G-B3Z8Y8KLW3',
  );
}
